name: raftstereo
channels:
  - pytorch
  - nvidia
  - bioconda
  - defaults
dependencies:
  - python=3.10.12
  - cuda-toolkit=12.2
  - matplotlib
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - opt_einsum
  - imageio
  - scikit-image
  - p7zip
  - pip
  - pip:
    - /home/auv/torch_wheels/torch-2.3.0-cp310-cp310-linux_aarch64.whl
    - /home/auv/torch_wheels/torchvision-0.18.0a0+6043bc2-cp310-cp310-linux_aarch64.whl
    - /home/auv/torch_wheels/torchaudio-2.3.0+952ea74-cp310-cp310-linux_aarch64.whl